# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats', models.ManyToManyField(related_name='team_chats', to='premierleagueapp.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeamscore', models.IntegerField(blank=True, default=0)),
                ('awayteamscore', models.IntegerField(blank=True, default=0)),
                ('weather', models.CharField(max_length=200)),
                ('weathericon', models.ImageField(blank=True, upload_to=b'weather')),
                ('mintemp', models.IntegerField(blank=True)),
                ('maxtemp', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to=b'team')),
                ('stadiumname', models.CharField(max_length=200)),
                ('stadiumloc', models.CharField(max_length=200)),
                ('apiteamid', models.IntegerField(blank=True)),
                ('apiteamname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='followings',
            name='followings',
            field=models.ManyToManyField(related_name='users_teamfollowings', to='premierleagueapp.Team'),
        ),
        migrations.AddField(
            model_name='followings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='awayteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='premierleagueapp.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='hometeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='premierleagueapp.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierleagueapp.Fixture'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierleagueapp.Team'),
        ),
    ]
